inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Rails/SkipsModelValidations:
  Enabled: true

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4

# Additional Rails-specific configurations
Rails/FilePath:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/HelperInstanceVariable:
  Enabled: true

Rails/UnknownEnv:
  Enabled: true
  Environments:
    - development
    - test
    - production
    - staging

Rails/UnusedIgnoredColumns:
  Enabled: true

Rails/Validation:
  Enabled: true

# Performance and style improvements
Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Disable some overly strict rules
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# RSpec specific improvements
RSpec/DescribeClass:
  Enabled: true

RSpec/DescribeMethod:
  Enabled: true

RSpec/EmptyLineAfterExample:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterSubject:
  Enabled: true

RSpec/LetSetup:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 3

RSpec/RepeatedDescription:
  Enabled: true

RSpec/SubjectStub:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: true
