---
reason: We are currently doing maintenance on the NELP application <small>(code 241017)</small>
allowed_paths:
allowed_ips:
# UMVPN - All Traffic or UMVPN - Only U-M Traffic range
- 35.7.0.0/18
response_code: 503
retry_after: 3600
